# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\Domain\Model\Id:
            resource_tags: ['app.domain.model.id']

        App\Shared\Infrastructure\ModuleExtension:
            resource_tags:
                - name: 'container.excluded'
                  source: "because it's a container extension"

    App\:
        resource: '../src/'
