doctrine:
    dbal:
        types:
            App\Catalog\Room\Domain\Model\RoomId: App\Shared\Infrastructure\Persistence\Doctrine\DBAL\Type\UidType
    orm:
        mappings:
            Catalog\Room:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Catalog/Room/Domain/Model'
                prefix: 'App\Catalog\Room\Domain\Model'
                alias: 'Catalog\Room'
